### ISSUE TITLE
I'm just a draft waiting to be real

### ISSUE THREAD

**Issue by jayspadie** [unicorns-r-us/test-repo#87]
This is the fine description.  Is the task list working?

## wut

More stuff 
Information added from the side-panel

https://github.com/unicorns-r-us/test-repo/issues/87#tasklist-block-f8b49043-858a-4a80-9718-3728cd34939a

**Comment by jayspadie** [comment]
Just some other #22

**Comment by krhkt** [comment]
the comment to clarify what was not clear. now we can all move forward following a clear path

**Comment by krhkt** [comment]
self referential issue https://github.com/unicorns-r-us/test-repo/issues/87

- #97
